set LIBGIT2DIR=%~dp0\..\ext\libgit2


set OPTS=
set OPTS=%OPTS% -DCMAKE_GENERATOR_PLATFORM=x64
set OPTS=%OPTS% -DBUILD_CLAR=0
set OPTS=%OPTS% -DUSE_SSH=0
set OPTS=%OPTS% -DUSE_OPENSSL=0

set DBGOPTS=
set DBGOPTS=%DBGOPTS% -DSTATIC_CRT=0
set DBGOPTS=%DBGOPTS% -DMSVC_CRTDBG=1
set DBGOPTS=%DBGOPTS% -DBUILD_SHARED_LIBS=1
set DBGOPTS=%DBGOPTS% -DCMAKE_CONFIGURATION_TYPES=Debug
set DBGOPTS=%DBGOPTS% -DCMAKE_INSTALL_PREFIX=%~dp0\build\debug64

set RELOPTS=
set RELOPTS=%RELOPTS% -DSTATIC_CRT=1
set RELOPTS=%RELOPTS% -DMSVC_CRTDBG=0
set RELOPTS=%RELOPTS% -DBUILD_SHARED_LIBS=0
set RELOPTS=%RELOPTS% -DCMAKE_CONFIGURATION_TYPES=Release
set RELOPTS=%RELOPTS% -DCMAKE_INSTALL_PREFIX=%~dp0\build\release64

set CCD=%CD%

mkdir debug
if '%ERRORLEVEL%'=='0' cd debug
if '%ERRORLEVEL%'=='0' cmake %OPTS% %DBGOPTS% %LIBGIT2DIR%
if '%ERRORLEVEL%'=='0' cd ..
if '%ERRORLEVEL%'=='0' mkdir release
if '%ERRORLEVEL%'=='0' cd release
if '%ERRORLEVEL%'=='0' cmake %OPTS% %RELOPTS% %LIBGIT2DIR%

cd %CCD%
